### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by pvklink** [madmicio/ampli-panel-card#10]
Is it possible to style this card?
I like this card and want the show the card on a small wall screen and the right part (volume etc) is not showed, you have to scroll)
i tried to use 
                style: |
                  ha-card {
                    height: 200px !important; 
                    widt: 200px !important; 
                  }

but that does not work

**Comment by GaupeLnx** [comment]
Yes, I love the design but  it seems to me like this card is designed for a bigger size screen only? . 
I would for example love to use it on a mobile device (Even if it would only work in landscape mode.)

**Comment by madmicio** [comment]
a new release  will be published soon.  provides the options of: original size, autosize and scale.

**Comment by madmicio** [comment]
new release released.
update me on any malfunctions

**Comment by pvklink** [comment]
Thanks!

Will test it this week

**Comment by pvklink** [comment]
It works perfect, tested the autosize on my pc browser and my small rpi screen panel
