### ISSUE TITLE
Problem with view

### ISSUE THREAD

**Issue by cucpo** [madmicio/ampli-panel-card#3]
Hi. I have a problem with the view in Lovelace. I only see the left part of the receiver. Otherwise - great work
![ampli](https://user-images.githubusercontent.com/6134650/84605151-65d76400-ae9b-11ea-94c0-1a8bcf3ac811.JPG)

**Comment by schoenof** [comment]
does not show anything for me....when I refresh I see some things being rendered but then immediately switch to all black....I have tried both light and dark themes but screen is just empty (either black or white matching theme)....

**Comment by madmicio** [comment]
> Hi. I have a problem with the view in Lovelace. I only see the left part of the receiver. Otherwise - great work
> ![ampli](https://user-images.githubusercontent.com/6134650/84605151-65d76400-ae9b-11ea-94c0-1a8bcf3ac811.JPG)

panel: true required or you can you it in a popup

**Comment by madmicio** [comment]
the theme does not influence the card.
post the configuration,
remember that the page must have the panel: true option
but you should have seen at least a piece of it anyway.

**Comment by passie** [comment]
I have similar problems. 
When I add 
```
entity: media_player.denon_avr_x4500h
type: 'custom:ampli-panel-card'
name: zone 1
brand: Denon
info: AV Surround Receiver X4500H
```
within the preview the receiver is visible. But after pressing save it's not visible. What am I doing wrong?

regard,
Passie

**Comment by vageesh79** [comment]
I am also getting same issue. It shows in preview but nothing after that. If i check raw config it shows the configuration.

**Comment by cucpo** [comment]
> the theme does not influence the card.
> post the configuration,
> remember that the page must have the panel: true option
> but you should have seen at least a piece of it anyway.

Hi madmicio
With option panel:true it is OK.
Thx

**Comment by moseisleydk** [comment]
Work only in Panel mode ...

**Comment by Omnimercador** [comment]
In my case, panel mode: false works; panel mode: true doesn't load the display at all.... Marantz 5013.

**Comment by mcgnai** [comment]
Ciao, io ho un amplificatore yamaha rx v2700 e non ha integrazione nativa con HA come media Player. Allora ho creato un media Player con smsrtir+ broadlink e memorizzato i codici ir dell'amply. Quando vado però ad integrare il media Player con la card vedo tutta la sezione degli input ma non vedo le altre scritte del display tipo stereo, dolly ecc. Probabilmente dipende da come è la struttura del media Player. Si può vedere come è il tuo media Player della marantz in modo da copire i comandi, il mio per esempio è così: 
![Screenshot_20211006-182701_Chrome](https://user-images.githubusercontent.com/31455181/136244892-1c64e073-fa2d-4c2a-8937-eb4777b9c87c.jpg)

**Comment by mcgnai** [comment]
Ciao, io ho un amplificatore yamaha rx v2700 e non ha integrazione nativa con HA come media Player. Allora ho creato un media Player con smsrtir+ broadlink e memorizzato i codici ir dell'amply. Quando vado però ad integrare il media Player con la card vedo tutta la sezione degli input ma non vedo le altre scritte del display tipo stereo, dolly ecc. Probabilmente dipenderà da come è la struttura del media Player. Si può vedere come è il tuo media Player della marantz in modo da copire i comandi, il mio per esempio è così:



Ciao, io ho un amplificatore yamaha rx v2700 e non ha integrazione nativa con HA come media Player. Allora ho creato un media Player con smsrtir+ broadlink e memorizzato i codici ir dell'amply. Quando vado però ad integrare il media Player con la card vedo tutta la sezione degli input ma non vedo le altre scritte del display tipo stereo, dolly ecc. Probabilmente dipenderà da come è la struttura del media Player. Si può vedere come è il tuo media Player della marantz in modo da copire i comandi, il mio per esempio è così:



Ciao, io ho un amplificatore yamaha rx v2700 e non ha integrazione nativa con HA come media Player. Allora ho creato un media Player con smsrtir+ broadlink e memorizzato i codici ir dell'amply. Quando vado però ad integrare il media Player con la card vedo tutta la sezione degli input ma non vedo le altre scritte del display tipo stereo, dolly ecc. Probabilmente dipenderà da come è la struttura del media Player. Si può vedere come è il tuo media Player della marantz in modo da copire i comandi, il mio per esempio è così:


![20211006_182917](https://user-images.githubusercontent.com/31455181/136245271-3ebc91b4-2167-4f88-8640-9e44a8c03f53.jpg)

**Comment by madmicio** [comment]
Hai fatto un bel lavoro con i codici.
La mia card visualizza nel display gli attributi che l'integrazione legge dal marantz.
Purtroppo se non c'è integrazione non puoi visualizzare nulla sul display.

Anzi teoricamente potresti simulare le info, ma sarebbe un lavoro enorme e sopratutto se cambi sorgente o qualsiasi impostazione da telecomando fisico non avresti il display aggiornato.

Purtroppo senza integrazione hai fatto il massimo.
