### ISSUE TITLE
Zone 2

### ISSUE THREAD

**Issue by Omnimercador** [madmicio/ampli-panel-card#5]
Is it possible to configure zone 1 / zone 2 of the actual receiver? In the example config, it looks like zone 2 refers to a different device?

**Comment by BebeMischa** [comment]
Yes, I just did exactly that.

**Comment by madmicio** [comment]
> Is it possible to configure zone 1 / zone 2 of the actual receiver? In the example config, it looks like zone 2 refers to a different device?

No. Zone 2 of the same device!
