### ISSUE TITLE
Only half of the controls is functional

### ISSUE THREAD

**Issue by BebeMischa** [madmicio/ampli-panel-card#6]
Hi, I just have installed this card for my Denon AVR X3600h. It works only partially.

Things that work fine:
Power main zone
Power zone 2
Volume
Mute
Zone selector
Display

Things that do not work:
All the buttons on Input selector (correct names are read, but clicking does nothing)
All the buttons on Sound mode selector (again, names are correct read, clicking does nothing)

Installed on HA supervised, all software is most recent versions.

The problem is with all the buttons inside the yellow marker.

![image](https://user-images.githubusercontent.com/73079275/168880792-d814d229-a16f-4dc5-86de-f57f930cba05.png)

Can you, guys, please, have a look, what is wrong?

Thank you very much.

Mischa

**Comment by BebeMischa** [comment]
@madmicio @PiotrMachowski Guys, please, would you just give some sign of life?

**Comment by PiotrMachowski** [comment]
@BebeMischa as you can see on my GitHub profile I'm quite alive. I'm not active here because I don't use this card

**Comment by BebeMischa** [comment]
So, is there maybe a way, we can get this working together? It will be fine not letting this nice peace o work die...

**Comment by PiotrMachowski** [comment]
@BebeMischa maybe it's a compatibility issu between hardware expected by the card and your media_player?
@madmicio does it still work for you?

**Comment by BebeMischa** [comment]
Well, as there is no compatible devices list anywhere, I can't say...
I do have a list of supported commands for this model, if that helps ;-)

**Comment by BebeMischa** [comment]
I still would love to get this going strong again... ;-)

**Comment by BebeMischa** [comment]
Can we, please, have a look at this?

**Comment by madmicio** [comment]
> @BebeMischa maybe it's a compatibility issu between hardware expected by the card and your media_player? @madmicio does it still work for you?

no it doesn't work, there is a problem with the source nomenclature

**Comment by BebeMischa** [comment]
So, can we bundle our powers and try to solve it?

**Comment by BebeMischa** [comment]
Still hoping...

**Comment by chichi1967** [comment]
Hi,
after debugging the code I found that there is a an error in 3 lines ....

2x.   }}}>${source}</button>
1x.   }}}>${sound}</button>

as soon as one } is removed in all of this lines the source and sound buttons are working as intended

**Comment by madmicio** [comment]
Thanks a lot, I could never find the time to check. I'll fix the code right away

**Comment by BebeMischa** [comment]
Thank you so much for the fix, @madmicio
