### ISSUE TITLE
Possible to regard other states as 'on'?

### ISSUE THREAD

**Issue by Scoff123** [madmicio/ampli-panel-card#8]
Thanks very much for this awesome card. I am using it with my Yamaha RX-V675 AV Receiver. The integration that I am using for my receiver in Home Assistant is the one provided here:

https://github.com/mvdwetering/yamaha_ynca

Using this integration, when the receiver is powered on, it has a reported state of 'idle' rather than 'on'. Unfortunately, if I try to use this ampli-panel-card, it does not show that the receiver is on, due to it expecting an 'on' state from the media player entity. 

Is it possible to include the state of 'idle' as regarding the entity as being 'on'?

**Comment by madmicio** [comment]
please try the new version 2.0 and let me know if it works now

**Comment by madmicio** [comment]
{{ device_attr("media_player.marantz_sr6010", "identifiers") | first | first }}

can you use this code in models replacing your mediaplayer entity and tell me what it gives you back?

**Comment by Scoff123** [comment]
Hi @madmicio , is there any more info I can give you to help with this? Happy to provide any other info needed.

**Comment by madmicio** [comment]
Thanks, your info is precious.  I stopped waiting for the card to become hacs default.  today it is, now I can resume development

**Comment by madmicio** [comment]
please let me know if the editor works properly with the new update.

**Comment by Scoff123** [comment]
OK thanks, I deleted the old version of the card and installed the latest version, but am still unable to pick my receiver because after picking the 'yamaha network receivers' option from the AV Receivers config option menu, there is nothing to choose in the next drop down,  for 'A- Receiver entity' just dashes like this:

![Screenshot_20240102_192835_Home Assistant](https://github.com/madmicio/ampli-panel-card/assets/96984460/b8e54442-cb74-4ee2-9ea5-60f24eb483f0)
